
services:
  redis:
    image: redis:7-alpine
    hostname: cacheq
    ports:
      - 6379:6379

  chatbot:
    hostname: chatbot
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_REDIS_HOSTS: redis://cacheq:6379
      QUARKUS_LANGCHAIN4J_OPENAI_API_KEY: "xxxx"
      QUARKUS_LANGCHAIN4J_OPENAI_ORGANIZATION_ID: xxxxxx
    ports:
      - 8080:8080

networks:
  default: